repos:
  - repo: https://github.com/pycqa/isort
    rev:  5.12.0
    hooks:
      - id: isort
        args: [
          '--line-length', '79',
          '--profile', 'black'
        ]

  - repo: https://github.com/myint/autoflake
    rev: v2.3.1
    hooks:
      - id: autoflake
        args: [
          '--in-place',
          '--remove-unused-variables',
          '--remove-all-unused-imports'
        ]
        exclude: __init__.py

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        types: [
          'python'
        ]
        args: [
          '--line-length', '79'
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2
    hooks:
    - id: mypy
      args: [
        '--allow-untyped-decorators',
        '--allow-subclassing-any',
        '--explicit-package-bases',
        '--follow-imports','skip',
        '--implicit-reexport',
        '--ignore-missing-imports',
        '--namespace-packages',
        '--show-error-codes',
        '--strict'
      ]
      additional_dependencies: [
        'types-requests'
      ]
      exclude: 'ctfd_setup/configuration.py'

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    - id: pydocstyle
      additional_dependencies: [
        'tomli'
      ]
      args: [
        '--ignore', 'D213,D203,D204,D416'
      ]
      exclude: 'ctdf_setup/__init__.py'

  - repo: local
    hooks:
    - id: pycodestyle
      name: pycodestyle
      entry: pycodestyle
      language: system
      args: [
        '--exclude', '*init*',
        '--ignore', 'E722,E126',
        '--max-line-length', '80'
      ]
      types: [
        'python'
      ]

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.9
    hooks:
    - id: bandit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: check-docstring-first
    - id: check-added-large-files
    - id: check-yaml
      args: [
        '--allow-multiple-documents'
      ]
